
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ru.sonarplus.kernel.sqlobject.sql_parse;

/** CUP generated class containing symbol constants. */
public class SqlParserSym {
  /* terminals */
  public static final int AS = 2;
  public static final int IDENTIFIER = 89;
  public static final int FROM = 5;
  public static final int TIME = 42;
  public static final int TIMESTAMP = 35;
  public static final int MONTH = 59;
  public static final int TIMEZONE_MINUTE = 65;
  public static final int ROWS = 86;
  public static final int ASC = 23;
  public static final int PARENT_R = 48;
  public static final int LIKE = 14;
  public static final int PARENT_L = 47;
  public static final int SECOND = 63;
  public static final int HOUR = 61;
  public static final int YEAR = 58;
  public static final int COMMA = 3;
  public static final int ALL = 75;
  public static final int FIRST = 85;
  public static final int SUBORD_DIRECT = 38;
  public static final int FALSE = 26;
  public static final int NOT = 11;
  public static final int PLUS_MINUS = 90;
  public static final int TIMEZONE_HOUR = 64;
  public static final int THEN = 46;
  public static final int TO_CODE = 49;
  public static final int EXTRACT = 57;
  public static final int WHEN = 28;
  public static final int EXCEPT = 76;
  public static final int INTO = 67;
  public static final int SELECT = 4;
  public static final int NUMBER = 91;
  public static final int CROSS_JOIN_OPERATOR = 94;
  public static final int GREAT_EQUAL = 53;
  public static final int TRUE = 25;
  public static final int SUBORD = 31;
  public static final int EXISTS = 29;
  public static final int UNION = 74;
  public static final int EQUAL = 50;
  public static final int DELETE = 69;
  public static final int STAR = 6;
  public static final int ESCAPE = 73;
  public static final int DIV = 12;
  public static final int CONCAT = 13;
  public static final int ELSE = 21;
  public static final int MINUTE = 62;
  public static final int DOT = 7;
  public static final int GREAT = 55;
  public static final int BACK_QUOTE = 56;
  public static final int SUBORD_DIRECT_OR_EQUAL = 40;
  public static final int SCALAR = 30;
  public static final int NULL = 27;
  public static final int EOF = 0;
  public static final int BETWEEN = 15;
  public static final int COMMENT = 92;
  public static final int REGEXP_MATCH = 82;
  public static final int INTERSECT = 78;
  public static final int WHERE = 8;
  public static final int DEFAULT = 81;
  public static final int OFFSET = 83;
  public static final int LEAF_OR_EQUAL = 37;
  public static final int MINUS = 77;
  public static final int IS = 18;
  public static final int FETCH = 84;
  public static final int OVER = 22;
  public static final int IN = 17;
  public static final int DATE = 41;
  public static final int OR = 9;
  public static final int SET = 71;
  public static final int error = 1;
  public static final int NOT_EQUAL = 51;
  public static final int GROUP_BY = 45;
  public static final int ON = 16;
  public static final int DESC = 24;
  public static final int ONLY = 87;
  public static final int END = 19;
  public static final int VALUES = 68;
  public static final int LESS_EQUAL = 52;
  public static final int JOIN_OPERATOR = 93;
  public static final int DAY = 60;
  public static final int CASE = 20;
  public static final int ORDER_BY = 33;
  public static final int CYCLE = 79;
  public static final int UPDATE = 70;
  public static final int INSERT = 66;
  public static final int LEAF = 43;
  public static final int STRING = 88;
  public static final int LESS = 54;
  public static final int AND = 10;
  public static final int TO = 80;
  public static final int SUBORD_OR_EQUAL = 39;
  public static final int PARTITION_BY = 36;
  public static final int WITH = 44;
  public static final int CALL = 72;
  public static final int HAVING = 32;
  public static final int DISTINCT = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AS",
  "COMMA",
  "SELECT",
  "FROM",
  "STAR",
  "DOT",
  "WHERE",
  "OR",
  "AND",
  "NOT",
  "DIV",
  "CONCAT",
  "LIKE",
  "BETWEEN",
  "ON",
  "IN",
  "IS",
  "END",
  "CASE",
  "ELSE",
  "OVER",
  "ASC",
  "DESC",
  "TRUE",
  "FALSE",
  "NULL",
  "WHEN",
  "EXISTS",
  "SCALAR",
  "SUBORD",
  "HAVING",
  "ORDER_BY",
  "DISTINCT",
  "TIMESTAMP",
  "PARTITION_BY",
  "LEAF_OR_EQUAL",
  "SUBORD_DIRECT",
  "SUBORD_OR_EQUAL",
  "SUBORD_DIRECT_OR_EQUAL",
  "DATE",
  "TIME",
  "LEAF",
  "WITH",
  "GROUP_BY",
  "THEN",
  "PARENT_L",
  "PARENT_R",
  "TO_CODE",
  "EQUAL",
  "NOT_EQUAL",
  "LESS_EQUAL",
  "GREAT_EQUAL",
  "LESS",
  "GREAT",
  "BACK_QUOTE",
  "EXTRACT",
  "YEAR",
  "MONTH",
  "DAY",
  "HOUR",
  "MINUTE",
  "SECOND",
  "TIMEZONE_HOUR",
  "TIMEZONE_MINUTE",
  "INSERT",
  "INTO",
  "VALUES",
  "DELETE",
  "UPDATE",
  "SET",
  "CALL",
  "ESCAPE",
  "UNION",
  "ALL",
  "EXCEPT",
  "MINUS",
  "INTERSECT",
  "CYCLE",
  "TO",
  "DEFAULT",
  "REGEXP_MATCH",
  "OFFSET",
  "FETCH",
  "FIRST",
  "ROWS",
  "ONLY",
  "STRING",
  "IDENTIFIER",
  "PLUS_MINUS",
  "NUMBER",
  "COMMENT",
  "JOIN_OPERATOR",
  "CROSS_JOIN_OPERATOR"
  };
}

